version: '3'
services:
  bot:
    image: btctradingbot:0.24
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:3000'
    expose:
      - '3000'
    volumes:
      - /srv/orders.db:/bot/orders.db
