version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:3000'
    expose:
      - '3000'
    volumes:
      - /srv/orders.json:/bot/orders.json
